In [1]:
import numpy as np

#1D array
list1 = [0,1,2,3]
array1 = np.array(list1)
array1+2

array([2, 3, 4, 5])

In [2]:
list2 = [[1,1,1],[2,2,2],[3,3,3]]
array2d = np.array(list2, dtype = 'float')

array2d

type(array2d)

array2d.dtype

dtype('float64')

In [3]:
array2d.size

array2d.ndim

array2d.shape

array2d.astype('float')

 


array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [4]:
cutarray = array2d[::-1]
cutarray

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [5]:
cutarray.squeeze()

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [6]:
cutarray[0:3,1:3]

array([[3., 3.],
       [2., 2.],
       [1., 1.]])

# , repetition and random number


In [7]:
np.arange(1,5)

array([1, 2, 3, 4])

In [8]:
a = np.random.randint(1,50,5)
a

array([36, 39,  7, 33, 43])

## concat



In [9]:
arr1 = np.zeros([4,4])
arr2 = np.ones([4,4])
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.concatenate([arr1,arr2], axis = 0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Sort


In [11]:
arr3 = np.random.randint(1,50, size =[10,5])
arr3

array([[ 3, 35, 15,  3, 35],
       [28, 34, 38, 21,  8],
       [39, 26,  6, 15, 22],
       [30, 49,  8, 45, 43],
       [30, 43, 40, 47, 48],
       [29, 29, 16, 21, 18],
       [14, 10,  5, 25,  6],
       [19, 39, 47, 31, 11],
       [28, 19,  8, 21, 49],
       [46, 46, 18, 14,  5]])

In [15]:
np.sort(arr3, axis = 0)
arr3

array([[ 3, 35, 15,  3, 35],
       [28, 34, 38, 21,  8],
       [39, 26,  6, 15, 22],
       [30, 49,  8, 45, 43],
       [30, 43, 40, 47, 48],
       [29, 29, 16, 21, 18],
       [14, 10,  5, 25,  6],
       [19, 39, 47, 31, 11],
       [28, 19,  8, 21, 49],
       [46, 46, 18, 14,  5]])

In [24]:
sortedIndex = arr3[:,0].argsort()
sortedIndex

array([0, 6, 7, 1, 8, 5, 3, 4, 2, 9], dtype=int64)

In [25]:
arr3[sortedIndex]

array([[ 3, 35, 15,  3, 35],
       [14, 10,  5, 25,  6],
       [19, 39, 47, 31, 11],
       [28, 34, 38, 21,  8],
       [28, 19,  8, 21, 49],
       [29, 29, 16, 21, 18],
       [30, 49,  8, 45, 43],
       [30, 43, 40, 47, 48],
       [39, 26,  6, 15, 22],
       [46, 46, 18, 14,  5]])