In [7]:
list2 = [[1,1,1],[2,2,2],[3,3,3]]
array2d = np.array(list2, dtype = 'float')

array2d

#type(array2d)

#array2d.dtype

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [8]:
array2d.size

array2d.ndim

array2d.shape

array2d.astype('float')

 


array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [9]:
cutarray = array2d[::-1]
cutarray

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])